version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install Latest Packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
            name: Install AWS CLI
            command: |
                cd .circleci
                chmod +x awscliInstall.sh
                ./awscliInstall.sh
      - run:
            name: Install Dependencies
            command: mvn dependency:go-offline
      - run:
          name: Run Tests
          command: mvn package
      - run:
          name: Build Artifacts
          command: |
            pwd
            ls -al
            mvn clean install
            cd target/
            ls -al
            cd ../../..
            pwd
      - run:
          name: Zip All Artifacts
          command: |
            mkdir -p artifact
            cd artifact
            ls -al
            touch 777 deploy.txt
      - run:
           name: Upload Artifact to Lambda S3 Bucket
           command: |
             export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
             export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
             export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
             aws s3 cp /home/circleci/project/target/PasswordTokenGenerator.jar s3://${LAMBDA_BUCKET_NAME} --region us-east-1
      - run:
          name: Deploy Latest Lambda Function
          command: |
            aws lambda update-function-code --function-name  ${LAMBDA_FUNCTION_NAME}  --s3-bucket ${LAMBDA_BUCKET_NAME} --s3-key PasswordTokenGenerator.jar --region us-east-1 > deploy.txt
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master